---
- hosts: linux
  become: yes
  tasks:
  - name: create fact directory
    file:
      path: /etc/ansible/facts.d
      state: directory
      recurse: yes
  - name: copy the fact script to node
    copy:
      src: datetime.sh
      dest: /etc/ansible/facts.d/date_time.fact
      mode: 0755
  - name: reload the fact
    setup:
      filter: ansible_local
  - name: print the custom fact
    debug:
      msg: " date in unix format {{ ansible_local.date_time }}"
